// Mocks generated by Mockito 5.4.6 from annotations
// in lumisovellus/test/unit/features/map/services/snow_types_service_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:dio/dio.dart' as _i2;
import 'package:lumisovellus/core/network/api_client.dart' as _i4;
import 'package:lumisovellus_api/lumisovellus_api.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeDio_0 extends _i1.SmartFake implements _i2.Dio {
  _FakeDio_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSegmentsApi_1 extends _i1.SmartFake implements _i3.SegmentsApi {
  _FakeSegmentsApi_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeReviewsApi_2 extends _i1.SmartFake implements _i3.ReviewsApi {
  _FakeReviewsApi_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeUsersApi_3 extends _i1.SmartFake implements _i3.UsersApi {
  _FakeUsersApi_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeWeatherApi_4 extends _i1.SmartFake implements _i3.WeatherApi {
  _FakeWeatherApi_4(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeSnowTypesApi_5 extends _i1.SmartFake implements _i3.SnowTypesApi {
  _FakeSnowTypesApi_5(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeHelpEventsApi_6 extends _i1.SmartFake implements _i3.HelpEventsApi {
  _FakeHelpEventsApi_6(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeAuthenticationApi_7 extends _i1.SmartFake
    implements _i3.AuthenticationApi {
  _FakeAuthenticationApi_7(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeResponse_8<T> extends _i1.SmartFake implements _i2.Response<T> {
  _FakeResponse_8(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [ApiClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockApiClient extends _i1.Mock implements _i4.ApiClient {
  @override
  _i2.Dio get dio =>
      (super.noSuchMethod(
            Invocation.getter(#dio),
            returnValue: _FakeDio_0(this, Invocation.getter(#dio)),
            returnValueForMissingStub: _FakeDio_0(
              this,
              Invocation.getter(#dio),
            ),
          )
          as _i2.Dio);

  @override
  _i3.SegmentsApi get segments =>
      (super.noSuchMethod(
            Invocation.getter(#segments),
            returnValue: _FakeSegmentsApi_1(this, Invocation.getter(#segments)),
            returnValueForMissingStub: _FakeSegmentsApi_1(
              this,
              Invocation.getter(#segments),
            ),
          )
          as _i3.SegmentsApi);

  @override
  _i3.ReviewsApi get reviews =>
      (super.noSuchMethod(
            Invocation.getter(#reviews),
            returnValue: _FakeReviewsApi_2(this, Invocation.getter(#reviews)),
            returnValueForMissingStub: _FakeReviewsApi_2(
              this,
              Invocation.getter(#reviews),
            ),
          )
          as _i3.ReviewsApi);

  @override
  _i3.UsersApi get users =>
      (super.noSuchMethod(
            Invocation.getter(#users),
            returnValue: _FakeUsersApi_3(this, Invocation.getter(#users)),
            returnValueForMissingStub: _FakeUsersApi_3(
              this,
              Invocation.getter(#users),
            ),
          )
          as _i3.UsersApi);

  @override
  _i3.WeatherApi get weather =>
      (super.noSuchMethod(
            Invocation.getter(#weather),
            returnValue: _FakeWeatherApi_4(this, Invocation.getter(#weather)),
            returnValueForMissingStub: _FakeWeatherApi_4(
              this,
              Invocation.getter(#weather),
            ),
          )
          as _i3.WeatherApi);

  @override
  _i3.SnowTypesApi get snowTypes =>
      (super.noSuchMethod(
            Invocation.getter(#snowTypes),
            returnValue: _FakeSnowTypesApi_5(
              this,
              Invocation.getter(#snowTypes),
            ),
            returnValueForMissingStub: _FakeSnowTypesApi_5(
              this,
              Invocation.getter(#snowTypes),
            ),
          )
          as _i3.SnowTypesApi);

  @override
  _i3.HelpEventsApi get helpEvents =>
      (super.noSuchMethod(
            Invocation.getter(#helpEvents),
            returnValue: _FakeHelpEventsApi_6(
              this,
              Invocation.getter(#helpEvents),
            ),
            returnValueForMissingStub: _FakeHelpEventsApi_6(
              this,
              Invocation.getter(#helpEvents),
            ),
          )
          as _i3.HelpEventsApi);

  @override
  _i3.AuthenticationApi get auth =>
      (super.noSuchMethod(
            Invocation.getter(#auth),
            returnValue: _FakeAuthenticationApi_7(
              this,
              Invocation.getter(#auth),
            ),
            returnValueForMissingStub: _FakeAuthenticationApi_7(
              this,
              Invocation.getter(#auth),
            ),
          )
          as _i3.AuthenticationApi);

  @override
  void setToken(String? token) => super.noSuchMethod(
    Invocation.method(#setToken, [token]),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [SnowTypesApi].
///
/// See the documentation for Mockito's code generation for more information.
class MockSnowTypesApi extends _i1.Mock implements _i3.SnowTypesApi {
  @override
  _i5.Future<_i2.Response<_i3.ApiV1SnowTypesGet200Response>> apiV1SnowTypesGet({
    _i2.CancelToken? cancelToken,
    Map<String, dynamic>? headers,
    Map<String, dynamic>? extra,
    _i2.ValidateStatus? validateStatus,
    _i2.ProgressCallback? onSendProgress,
    _i2.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#apiV1SnowTypesGet, [], {
              #cancelToken: cancelToken,
              #headers: headers,
              #extra: extra,
              #validateStatus: validateStatus,
              #onSendProgress: onSendProgress,
              #onReceiveProgress: onReceiveProgress,
            }),
            returnValue:
                _i5.Future<
                  _i2.Response<_i3.ApiV1SnowTypesGet200Response>
                >.value(
                  _FakeResponse_8<_i3.ApiV1SnowTypesGet200Response>(
                    this,
                    Invocation.method(#apiV1SnowTypesGet, [], {
                      #cancelToken: cancelToken,
                      #headers: headers,
                      #extra: extra,
                      #validateStatus: validateStatus,
                      #onSendProgress: onSendProgress,
                      #onReceiveProgress: onReceiveProgress,
                    }),
                  ),
                ),
            returnValueForMissingStub:
                _i5.Future<
                  _i2.Response<_i3.ApiV1SnowTypesGet200Response>
                >.value(
                  _FakeResponse_8<_i3.ApiV1SnowTypesGet200Response>(
                    this,
                    Invocation.method(#apiV1SnowTypesGet, [], {
                      #cancelToken: cancelToken,
                      #headers: headers,
                      #extra: extra,
                      #validateStatus: validateStatus,
                      #onSendProgress: onSendProgress,
                      #onReceiveProgress: onReceiveProgress,
                    }),
                  ),
                ),
          )
          as _i5.Future<_i2.Response<_i3.ApiV1SnowTypesGet200Response>>);

  @override
  _i5.Future<_i2.Response<_i3.ApiV1SnowTypesPost201Response>>
  apiV1SnowTypesIdSecondaryPost({
    required String? id,
    required _i3.AddSecondarySnowTypesRequest? addSecondarySnowTypesRequest,
    _i2.CancelToken? cancelToken,
    Map<String, dynamic>? headers,
    Map<String, dynamic>? extra,
    _i2.ValidateStatus? validateStatus,
    _i2.ProgressCallback? onSendProgress,
    _i2.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#apiV1SnowTypesIdSecondaryPost, [], {
              #id: id,
              #addSecondarySnowTypesRequest: addSecondarySnowTypesRequest,
              #cancelToken: cancelToken,
              #headers: headers,
              #extra: extra,
              #validateStatus: validateStatus,
              #onSendProgress: onSendProgress,
              #onReceiveProgress: onReceiveProgress,
            }),
            returnValue:
                _i5.Future<
                  _i2.Response<_i3.ApiV1SnowTypesPost201Response>
                >.value(
                  _FakeResponse_8<_i3.ApiV1SnowTypesPost201Response>(
                    this,
                    Invocation.method(#apiV1SnowTypesIdSecondaryPost, [], {
                      #id: id,
                      #addSecondarySnowTypesRequest:
                          addSecondarySnowTypesRequest,
                      #cancelToken: cancelToken,
                      #headers: headers,
                      #extra: extra,
                      #validateStatus: validateStatus,
                      #onSendProgress: onSendProgress,
                      #onReceiveProgress: onReceiveProgress,
                    }),
                  ),
                ),
            returnValueForMissingStub:
                _i5.Future<
                  _i2.Response<_i3.ApiV1SnowTypesPost201Response>
                >.value(
                  _FakeResponse_8<_i3.ApiV1SnowTypesPost201Response>(
                    this,
                    Invocation.method(#apiV1SnowTypesIdSecondaryPost, [], {
                      #id: id,
                      #addSecondarySnowTypesRequest:
                          addSecondarySnowTypesRequest,
                      #cancelToken: cancelToken,
                      #headers: headers,
                      #extra: extra,
                      #validateStatus: validateStatus,
                      #onSendProgress: onSendProgress,
                      #onReceiveProgress: onReceiveProgress,
                    }),
                  ),
                ),
          )
          as _i5.Future<_i2.Response<_i3.ApiV1SnowTypesPost201Response>>);

  @override
  _i5.Future<_i2.Response<_i3.ApiV1SnowTypesPost201Response>>
  apiV1SnowTypesPost({
    required _i3.CreateSnowTypeRequest? createSnowTypeRequest,
    _i2.CancelToken? cancelToken,
    Map<String, dynamic>? headers,
    Map<String, dynamic>? extra,
    _i2.ValidateStatus? validateStatus,
    _i2.ProgressCallback? onSendProgress,
    _i2.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#apiV1SnowTypesPost, [], {
              #createSnowTypeRequest: createSnowTypeRequest,
              #cancelToken: cancelToken,
              #headers: headers,
              #extra: extra,
              #validateStatus: validateStatus,
              #onSendProgress: onSendProgress,
              #onReceiveProgress: onReceiveProgress,
            }),
            returnValue:
                _i5.Future<
                  _i2.Response<_i3.ApiV1SnowTypesPost201Response>
                >.value(
                  _FakeResponse_8<_i3.ApiV1SnowTypesPost201Response>(
                    this,
                    Invocation.method(#apiV1SnowTypesPost, [], {
                      #createSnowTypeRequest: createSnowTypeRequest,
                      #cancelToken: cancelToken,
                      #headers: headers,
                      #extra: extra,
                      #validateStatus: validateStatus,
                      #onSendProgress: onSendProgress,
                      #onReceiveProgress: onReceiveProgress,
                    }),
                  ),
                ),
            returnValueForMissingStub:
                _i5.Future<
                  _i2.Response<_i3.ApiV1SnowTypesPost201Response>
                >.value(
                  _FakeResponse_8<_i3.ApiV1SnowTypesPost201Response>(
                    this,
                    Invocation.method(#apiV1SnowTypesPost, [], {
                      #createSnowTypeRequest: createSnowTypeRequest,
                      #cancelToken: cancelToken,
                      #headers: headers,
                      #extra: extra,
                      #validateStatus: validateStatus,
                      #onSendProgress: onSendProgress,
                      #onReceiveProgress: onReceiveProgress,
                    }),
                  ),
                ),
          )
          as _i5.Future<_i2.Response<_i3.ApiV1SnowTypesPost201Response>>);

  @override
  _i5.Future<_i2.Response<_i3.ApiV1SnowTypesPrimaryGet200Response>>
  apiV1SnowTypesPrimaryGet({
    _i2.CancelToken? cancelToken,
    Map<String, dynamic>? headers,
    Map<String, dynamic>? extra,
    _i2.ValidateStatus? validateStatus,
    _i2.ProgressCallback? onSendProgress,
    _i2.ProgressCallback? onReceiveProgress,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#apiV1SnowTypesPrimaryGet, [], {
              #cancelToken: cancelToken,
              #headers: headers,
              #extra: extra,
              #validateStatus: validateStatus,
              #onSendProgress: onSendProgress,
              #onReceiveProgress: onReceiveProgress,
            }),
            returnValue:
                _i5.Future<
                  _i2.Response<_i3.ApiV1SnowTypesPrimaryGet200Response>
                >.value(
                  _FakeResponse_8<_i3.ApiV1SnowTypesPrimaryGet200Response>(
                    this,
                    Invocation.method(#apiV1SnowTypesPrimaryGet, [], {
                      #cancelToken: cancelToken,
                      #headers: headers,
                      #extra: extra,
                      #validateStatus: validateStatus,
                      #onSendProgress: onSendProgress,
                      #onReceiveProgress: onReceiveProgress,
                    }),
                  ),
                ),
            returnValueForMissingStub:
                _i5.Future<
                  _i2.Response<_i3.ApiV1SnowTypesPrimaryGet200Response>
                >.value(
                  _FakeResponse_8<_i3.ApiV1SnowTypesPrimaryGet200Response>(
                    this,
                    Invocation.method(#apiV1SnowTypesPrimaryGet, [], {
                      #cancelToken: cancelToken,
                      #headers: headers,
                      #extra: extra,
                      #validateStatus: validateStatus,
                      #onSendProgress: onSendProgress,
                      #onReceiveProgress: onReceiveProgress,
                    }),
                  ),
                ),
          )
          as _i5.Future<_i2.Response<_i3.ApiV1SnowTypesPrimaryGet200Response>>);
}
