stages:
  - lint
  - test
  - build

cache:
  paths:
    - /flutter/bin/cache/dart-sdk

# Define a job template for Flutter jobs
.flutter-template: &flutter-job
  image: ghcr.io/cirruslabs/flutter:3.19.3
  before_script:
    - cd 'Mobile snowledge/mobile_app'
    - flutter packages get
  only:
    - merge_requests 

lint-flutter:
  <<: *flutter-job
  stage: lint
  script:
    - echo "Flutter linting"
    - flutter analyze --no-fatal-infos

test-flutter:
  <<: *flutter-job
  stage: test
  script:
    - echo "Running Flutter unit tests..."
    - flutter test ./test/

build-flutter-apk:
  <<: *flutter-job
  stage: build
  script:
    - echo 'Building Android mobile Snowledge...'
    - flutter build apk --release
  only:
    - main
    - master    # Only build when merge into production

# Define a job template for Python job
.python-template: &python-job
  image: python:3.7
  before_script:
    - cd 'Mobile snowledge/Server/back_end'
    - python --version && pip --version
    - echo "Install required packages"
    - pip install -r requirements.txt
  only:
    - merge_requests 

test-python-db:
  <<: *python-job
  stage: test
  script:
    - echo "Testing backend database"
    - python test.databaseFunc.py

test-python-server:
  <<: *python-job
  stage: test
  script:
    - echo "Testing backend server"
    - python test.udpServer.py
