stages:
  - lint
  - test
  - build

default:
  image: cirrusci/flutter:3.7.0

cache:
  paths:
    - /flutter/bin/cache/dart-sdk

# Might want to add this part later, analyze code to see if any lint problem
lint:
  stage: lint
  script:
    - flutter analyze --no-fatal-infos    # Don't treat info as fatal so the pipeline won't fail

test:
  stage: test
  script:
    - cd 'Mobile snowledge/mobile_app'
    - flutter packages get
    - echo "Running unit tests..."
    - flutter test ./test/

build:
  stage: build
  script:
    - echo 'Building Android mobile Snowledge...'
    - cd 'Mobile snowledge/mobile_app'
    - flutter packages get
    - flutter build apk --release
