stages:
  # - lint
  - android_setup
  - test
  - coverage

default:
  image: cirrusci/flutter:3.7.0

cache:
  paths:
    - /flutter/bin/cache/dart-sdk

# Might want to add this part later, analyze code to see if any lint problem
# lint:
#   stage: lint
#   script:
#     - flutter analyze

android_setup:
  stage: android_setup
  variables:
    apiLevel: "27"
    target: "google_apis"
    arch: "x86"
    deviceName: "android_emulator"
    deviceType: "pixel"
  script:
    - sdkmanager "platform-tools" "platforms;android-${apiLevel}"
    - sdkmanager --install "system-images;android-${apiLevel};${target}${arch}"
    - sdkmanager --update
    - echo "y" | sdkmanager --licenses
    - sdkmanager --list
    - echo "no" | avdmanager -v create avd --force --name "${deviceName}" --package "system-images;android-${apiLevel};${target};${arch}" --tag "${target}" --sdcard 128M --device "${deviceType}"
    - emulator -avd "${deviceName}" -no-audio -no-window -no-snapstorage -no-snapshot -gpu swiftshader_indirect -no-boot-anim -no-accel -wipe-data -skip-adb-auth &
    - adb wait-for-device shell 'while [[ -z $(getprop sys.boot_completed) ]]; do sleep 1; done; input keyevent 82'
    - flutter doctor -v 

test:
  stage: test
  script:
    - cd 'Mobile snowledge/mobile_app'
    - pub global activate junitreport
    - export PATH="$PATH":"$HOME/.pub-cache/bin"
    - flutter pub get
    - flutter test --coverage --machine | tojunit > testreport.xml
  artifacts:
    reports:
      junit: testreport.xml
    paths:
      - coverage

coverage:
  stage: coverage
  script:
    - genhtml coverage/lcov.info --output=coverage
    - mv coverage/ public/
  artifacts:
    paths:
      - public