version: '3'
services:
  node-app:
    build:
      context: ./src  # Path to the directory containing your Node.js app Dockerfile
    ports:
      - "3000:3000"  # Map host port 8080 to container port 3000
    volumes:
      - ./node-app:/app-node  # Mount your Node.js app code into the container
    command: ["node", "app.js"]

  python-app:
    build:
      context: "./Mobile snowledge/Server" # Path to the directory containing your Python app Dockerfile
    environment:
      - APP_ENVIRONMENT=development
    ports:
      - "50943:50943"
    volumes:
      - ./python-app:/app-python  # Mount your Python app code into the container

  flutter-app:
    build:
      context: "./Mobile snowledge/mobile_app"  # Path to the directory containing your Flutter app Dockerfile
    ports:
      - "5037:5037"  # Map host port 8082 to container port 8082 (assuming Flutter runs on this port)
    environment:
      - APP_ENVIRONMENT=development
    volumes:
      - ./flutter-app:/app-flutter  # Mount your Flutter app code into the container
    command: ["flutter", "doctor"]
