// eslint-disable-next-line @typescript-eslint/no-unused-vars, unused-imports/no-unused-imports
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { cookies } from "next/headers";
import { NextIntlClientProvider } from "next-intl";
import Nav from "@/components/app-nav";
import AppSidebar from "@/components/app-sidebar";
import { SidebarInset, SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookieStore = await cookies()
  const defaultOpen = cookieStore.get("sidebar_state")?.value === "true"

  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <NextIntlClientProvider>
            <SidebarProvider defaultOpen={defaultOpen}>
              <div className="w-[100dvw] h-[100dvh] flex flex-row overflow-hidden">
            <AppSidebar />
            <SidebarInset className="relative flex flex-col gap-2 flex-1">
              <div className="w-full flex justify-start items-center absolute z-999 p-2">
                <SidebarTrigger className="bg-background" />
              </div>
              <div className="flex-1 w-full h-full rounded-xl overflow-clip">
                {children}
              </div>
              <div className="w-full flex justify-center absolute bottom-1 p-2 z-9999">
                <Nav />
              </div>
            </SidebarInset>
              </div>
            </SidebarProvider>
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
