# Use an official Python runtime as the base image
FROM python:3.9

# Set the working directory inside the container
WORKDIR /back_end

# Copy the application files into the container
COPY . .

# Install any Python dependencies (if required)
RUN cd back_end && pip install -r requirements.txt
EXPOSE 50943

# Set environment variables (e.g., APP_ENVIRONMENT)
ENV APP_ENVIRONMENT=development
CMD ["python", "back_end/server.py"]
