FROM node:20.10.0

ARG DEBIAN_FRONTEND=noninteractive

# Install dependencies and tools
RUN apt-get update && apt-get upgrade -y && \
    echo "deb http://deb.debian.org/debian bookworm-backports main" > /etc/apt/sources.list.d/backports.list && \
    apt-get update && \
    apt-get install -y \
    watchman \
    wget \
    unzip \
    zip \
    curl \
    git-all \
    xz-utils \
    libglu1-mesa \
    libc6:amd64 libstdc++6:amd64 lib32z1 libbz2-1.0:amd64 && \
    rm -rf /var/lib/apt/lists/*

ENV JAVA_HOME=/opt/java/openjdk
ENV PATH="$JAVA_HOME/bin:$PATH"

RUN mkdir -p /opt/java && \
    curl -fsSL https://api.adoptium.net/v3/binary/latest/21/ga/linux/x64/jdk/hotspot/normal/eclipse -o /tmp/jdk21.tar.gz && \
    tar -xzf /tmp/jdk21.tar.gz -C /opt/java && \
    ln -s /opt/java/jdk-21*/ /opt/java/openjdk && \
    rm /tmp/jdk21.tar.gz

# Install Flutter CLI
RUN git clone https://github.com/flutter/flutter.git -b 3.35.0 /opt/flutter \
    && git config --global --add safe.directory /opt/flutter \
    && echo 'export PATH="$PATH:/opt/flutter/bin"' >> /etc/profile \
    && /opt/flutter/bin/flutter doctor

ENV PATH="/opt/flutter/bin:$PATH"

# Install Android SDK
ENV FLUTTER_NDK_VERSION=28.1.13356709
ENV ANDROID_SDK_ROOT=/opt/android-sdk
ENV ANDROID_HOME=/opt/android-sdk
ENV PATH=$PATH:$ANDROID_HOME/cmdline-tools/latest/bin:$ANDROID_HOME/platform-tools:$ANDROID_HOME/emulator

RUN mkdir -p $ANDROID_HOME/cmdline-tools \
    && cd $ANDROID_HOME \
    && wget https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip -O cmdline-tools.zip \
    && unzip cmdline-tools.zip -d cmdline-tools \
    && mv cmdline-tools/cmdline-tools $ANDROID_HOME/cmdline-tools/latest \
    && rm cmdline-tools.zip \
    && yes | sdkmanager --sdk_root=$ANDROID_HOME --licenses \
    && sdkmanager --sdk_root=$ANDROID_HOME \
        "platform-tools" \
        "platforms;android-35" "build-tools;35.0.0" \
        "platforms;android-36" "build-tools;36.1.0" \
        "cmake;3.22.1" \
        "ndk;${FLUTTER_NDK_VERSION}"
        
WORKDIR /workspace

CMD ["sleep", "infinity"]
