# Use an official Python runtime as the base image
FROM python:3.9

# Set the working directory inside the container
WORKDIR /app

# Copy the application files into the container
COPY . .

# Install any Python dependencies (if required)
RUN pip install -r requirements.txt
EXPOSE 50943

# Set environment variables (e.g., APP_ENVIRONMENT)
ENV APP_ENVIRONMENT=development
CMD ["python", "server.py"]
