// Mocks generated by Mockito 5.4.6 from annotations
// in lumisovellus/test/features/rescue/help_repository_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:lumisovellus/features/rescue/data/services/help_service.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeServiceHelpResponse_0 extends _i1.SmartFake
    implements _i2.ServiceHelpResponse {
  _FakeServiceHelpResponse_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [HelpService].
///
/// See the documentation for Mockito's code generation for more information.
class MockHelpService extends _i1.Mock implements _i2.HelpService {
  @override
  _i3.Future<_i2.ServiceHelpResponse> requestHelp(
    _i2.ServiceHelpRequest? request,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#requestHelp, [request]),
            returnValue: _i3.Future<_i2.ServiceHelpResponse>.value(
              _FakeServiceHelpResponse_0(
                this,
                Invocation.method(#requestHelp, [request]),
              ),
            ),
            returnValueForMissingStub:
                _i3.Future<_i2.ServiceHelpResponse>.value(
                  _FakeServiceHelpResponse_0(
                    this,
                    Invocation.method(#requestHelp, [request]),
                  ),
                ),
          )
          as _i3.Future<_i2.ServiceHelpResponse>);

  @override
  _i3.Future<void> cancelHelp(String? requestId) =>
      (super.noSuchMethod(
            Invocation.method(#cancelHelp, [requestId]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> completeHelp(String? requestId) =>
      (super.noSuchMethod(
            Invocation.method(#completeHelp, [requestId]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}
