// Mocks generated by Mockito 5.4.6 from annotations
// in lumisovellus/test/unit/features/map/repositories/snow_types_repository_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:lumisovellus/core/network/api_client.dart' as _i2;
import 'package:lumisovellus/features/map/data/services/snow_types_service.dart'
    as _i3;
import 'package:lumisovellus_api/lumisovellus_api.dart' as _i5;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeApiClient_0 extends _i1.SmartFake implements _i2.ApiClient {
  _FakeApiClient_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [SnowTypesService].
///
/// See the documentation for Mockito's code generation for more information.
class MockSnowTypesService extends _i1.Mock implements _i3.SnowTypesService {
  @override
  _i2.ApiClient get api =>
      (super.noSuchMethod(
            Invocation.getter(#api),
            returnValue: _FakeApiClient_0(this, Invocation.getter(#api)),
            returnValueForMissingStub: _FakeApiClient_0(
              this,
              Invocation.getter(#api),
            ),
          )
          as _i2.ApiClient);

  @override
  _i4.Future<List<_i5.SnowType>> fetchSnowTypes({
    String? bbox,
    String? search,
    DateTime? updatedSince,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#fetchSnowTypes, [], {
              #bbox: bbox,
              #search: search,
              #updatedSince: updatedSince,
            }),
            returnValue: _i4.Future<List<_i5.SnowType>>.value(<_i5.SnowType>[]),
            returnValueForMissingStub: _i4.Future<List<_i5.SnowType>>.value(
              <_i5.SnowType>[],
            ),
          )
          as _i4.Future<List<_i5.SnowType>>);
}
