# Use an official Node.js runtime as the base image
FROM node:14

# Set the working directory inside the container
WORKDIR /map-app

# Copy the package.json and package-lock.json files
COPY package*.json ./

# Install dependencies
RUN npm install

# Fix any audit issues
RUN npm audit fix

# Build the application
RUN npm build

# Set the working directory for running the app
WORKDIR /
EXPOSE 3000
EXPOSE 443
# Start the Node.js application
CMD ["node", "app.js"]
