name: PR -> frontend

on:
  pull_request:
    types: [opened, reopened, ready_for_review, synchronize]
    branches:
      - 'frontend'
  workflow_dispatch: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  validation:
    uses: ./.github/workflows/ci-reusable.yml
    with:
      coverage-threshold: 70
      audit-level: "critical"
    secrets: inherit