name: PR -> release (Integration)

on:
  pull_request:
    branches:
      - 'release/**'
      # TODO: Split backend and frontend development ci into own workflows
      # Can be done once npm run has separate test scripts for backend and frontend
      - 'frontend'

jobs:
  integration:
    uses: ./.github/workflows/ci-reusable.yml
    with:
      node-version: '20.10.0'
      coverage-threshold: 70
      run-build: true
      run-security-checks: true
      audit-level: "critical"
    secrets: inherit
