name: PR -> master (Release candidate)

on:
  pull_request:
    branches: [master]

jobs:
  rc:
    uses: ./.github/workflows/ci-reusable.yml
    with:
      node-version: '20.10.0'
      coverage-threshold: 80
      run-build: true
      run-heavy-lint: true
      run-security-checks: true
      audit-level: "high"
      run-smoke-e2e: true
    secrets: inherit