name: Push -> branch (all branches)

on:
  push:
    branches:
      - '**'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  integration:
    uses: ./.github/workflows/ci-reusable.yml
    with:
      coverage-threshold: 70
      run-heavy-lint: true
      run-security-checks: true
      audit-level: "high"
    secrets: inherit
