name: Push -> branch (all branches)

on:
  push:
    branches:
      - '**'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  full-stack-ci:
    uses: ./.github/workflows/combined-ci.yml
    secrets: inherit
