name: Push -> branch (all branches)

on:
  push:
    branches:
      - '**'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  rc:
    uses: ./.github/workflows/ci-reusable.yml
    with:
      coverage-threshold: 80
      run-build: true
      run-heavy-lint: true
      run-security-checks: true
      audit-level: "high"
      run-smoke-e2e: true
    secrets: inherit